<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * Implements hook_menu()
 *
 * @return array
 */
function gd_workflow_admin_menu () {

    $items = array();

    $items['cp/workflow'] = array(
        'page callback' => 'gd_workflow_admin_page_index',
        'access callback' => 'gd_workflow_admin_access',
        'type' => MENU_CALLBACK
    );

    return $items;
}

/**
 * Implements hook_gd_admin_sections()
 *
 * @return array
 */
function gd_workflow_admin_gd_admin_sections () {

    $items['workflow'] =  array(
        'name' => 'workflow',
        'title' => 'Workflow',
        'class' => 'WorkflowSection',
        'access' => 'gd_workflow_admin_access',
        'weight' => 4
    );

    return $items;
}

//  TODO Need to be configuration setting not blanket access for all admins. Example: Allow certain roles access to User controls
function gd_workflow_admin_access() {
    $allowed = ( gd_account_user_is_admin() || gd_account_user_is_any_datasource_admin() );
    drupal_alter('gd_workflow_admin_access', $allowed);

    return $allowed;
}

function gd_workflow_admin_library() {
    $libraries['GD_Admin_WorkflowSection'] = array(
        'title'   => 'GD Admin - Workflow Section',
        'version' => '',
        'js' => array(
            drupal_get_path('module','gd_workflow_admin').'/js/WorkflowSection.js' => array(),
            drupal_get_path('module','gd_workflow_admin').'/js/WorkflowModel.js' => array(),
            drupal_get_path('module','gd_workflow_admin').'/js/WorkflowIndexView.js' => array(),
            drupal_get_path('module','gd_workflow_admin').'/js/forms/WorkflowItemsForm.js' => array(),
            drupal_get_path('module','gd_workflow_admin').'/js/forms/WorkflowDatasourcesForm.js' => array(),
            drupal_get_path('module','gd_workflow_admin').'/js/forms/WorkflowOptionsForm.js' => array()
        ),
        'css' => array (
            drupal_get_path('module','gd_workflow_admin').'/css/WorkflowSection.css' => array('weight'=>1,'group'=>CSS_THEME)
        ),
        'dependencies' => array(
            array('gd_admin', 'GD_Admin')
        )
    );

    return $libraries;
}

function gd_workflow_admin_page_default () {
    $default = gd_admin_page_default();
    drupal_add_library('gd', 'fuelux');
    drupal_add_library('gd', 'jsTree');
    drupal_add_js(drupal_get_path('module','gd').'/js/component/tree/TreeView.js');
    drupal_add_library('gd_workflow_admin', 'GD_Admin_WorkflowSection');
    return $default;
}

function gd_workflow_admin_page_index () {
    return gd_workflow_admin_page_default();
}