<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * Implements hook_xautoload()
 *
 * @param \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter
 */
function gd_user_xautoload($adapter) {
    $adapter->add('GD','lib');
}

/*
 * Implements hook_enable
 */
function gd_user_enable() {
    variable_set('user_password_reset_timeout', 259200);
}

function gd_user_is_logged_in() {
    global $user;

    return $user->uid ? TRUE : FALSE;
}

function gd_user_get_config() {
    return variable_get('gd_user_config', array(
        'notify' => TRUE,
        'enabled_cron' => TRUE,
        'expiration' => array(
            'duration' => 31
        ),
        'notifications' => array(
            'user_reminder' => TRUE,
            'user_reminder_countdown' => 7
        )
    ));
}

function gd_user_get_inactivity_notice() {
    $config = gd_user_get_config();
    return "You are receiving this notice because your GovDashboard account on " . GOVDASH_HOST . " is about to become inactive in " . $config['notifications']['user_reminder_countdown'] . " days.\n\nYou will have to contact your site administrator to have your account reactivated.\n\nPlease feel free to contact us if you have any comments or concerns.";
}

function gd_user_get_inactivity_message() {
    return "You are receiving this notice because your GovDashboard account on " . GOVDASH_HOST . " is no longer active.\n\nYou will have to contact your site administrator to have your account reactivated.\n\nPlease feel free to contact us if you have any comments or concerns.";
}

function gd_user_is_notifications_toggled() {
    $config = gd_user_get_config();
    return $config['notify'] == 0 ? false : true;
}

function gd_user_inactive_warn_user($user) {
    if (!gd_user_is_notifications_toggled()) return;

    db_insert('gd_user_inactivity_warning')
      ->fields(array(
        'uid' => $user
      ))
      ->execute();

    gd_notification_send_notification($user, GD_NOTIFICATION_NOTICE, 'User Inactivity Warning', gd_user_get_inactivity_notice());
}

function gd_user_inactive($user) {
    if (!gd_user_is_notifications_toggled()) return;

    $account = user_load($user);
    user_save($account, array(
       'status' => 0
    ), 'user_automated_inactivity');

    db_delete('gd_user_inactivity_warning')
      ->condition('uid', $user, '=')
      ->execute();
    gd_notification_send_notification($user, GD_NOTIFICATION_NOTICE, 'User Inactivity Notice', gd_user_get_inactivity_message());
}

function gd_user_cron() {
    $config = gd_user_get_config();
    if (!$config['enabled_cron']) return;

    $currentTime = time();
    $expiration = $config['expiration']['duration'] * 86400;
    $accounts = entity_load('user');
    foreach ($accounts as $account) {
        if ($account->uid == 0) return;

        $lastAccess = $account->access;
        if ($lastAccess + $expiration <= $currentTime) {
            gd_user_inactive($account->uid);
        } else if ($config['notifications']['user_reminder']) {
            $countdown = $config['notifications']['user_reminder_countdown'] * 86400;
            if ($lastAccess + $expiration - $countdown <= $currentTime) {
                gd_user_inactive_warn_user($account->uid);
            }
        }
    }
}

function gd_user_menu() {
    $items = array();
    $items['admin/config/govdashboard/user'] = array(
        'title' => 'User Settings',
        'description' =>  'Configure global user settings.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('gd_user_admin_settings_form'),
        'file' => 'gd_user.admin.inc',
        'access arguments' => array('administer site configuration')
    );

    return $items;
}

function gd_user_user_insert(&$edit, $account, $category) {
    if ($account->uid == 1 || !gd_user_is_notifications_toggled()) return;

    $link = user_pass_reset_url($account);
    $message = "A site administrator at GovDashboard has created an account for you. Please click the following link to confirm your email and set your password.\n" . $link
      . "\nNote that the link can only be used once and will expire in 3 days.\n\nPlease feel free to contact us if you have any comments or concerns.\n\nThanks!";

    $configuration = array(
        'destination' => $account->uid,
        'type' => GD_NOTIFICATION_NOTICE,
        'message' => $message,
        'subject' => 'GovDashboard Account Created'
    );

    gd_notification_send($configuration);
}

function gd_user_user_update(&$edit, $account, $category) {
    if (!isset($edit['status']) || ($edit['status'] == $edit['original']->status) || $account->uid == 1 || !gd_user_is_notifications_toggled()) return;

    if ($edit['status']) {
        $link = user_pass_reset_url($account);
        $message = "Welcome to GovDashboard! Your account has been activated.\n\nUse following link to login to your GovDashboard account.\n" . $link . "\n\nusername: " . $account->name . "\npassword: Your password\n\nPlease feel free to contact us if you have any comments or concerns.\n\nThanks!";
    } else {
        $message = "You are receiving this notice because your GovDashboard account is no longer active.\nReason: Blocked by Site Admin.\n\nYou will have to contact your site administrator to have your account reactivated.\n\nPlease feel free to contact us if you have any comments or concerns.\nThanks!";
    }

    $configuration = array(
        'destination' => $account->uid,
        'type' => GD_NOTIFICATION_NOTICE,
        'message' => $message,
        'subject' => $edit['status'] ? 'Your GovDashboard Account Details' : 'GovDashboard account blocked'
    );

    gd_notification_send($configuration);
}

function gd_user_user_login(&$edit, $account) {
    db_delete('gd_user_inactivity_warning')
      ->condition('uid', $account->uid, '=')
      ->execute();
}
