<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


function data_controller_log_dp_log_message_listener() {
    $items[] = array(
        'classname' => 'ArrayLogMessageSlicer',
        'priority' => -70);
    $items[] = array(
        'classname' => 'TextLogMessageTrimmer',
        'priority' => -50);
    $items[] = array(
        'classname' => 'ExceptionLogMessageFormatter',
        'priority' => -30);
    $items[] = array(
        'classname' => 'PreservedTextLogMessageListener',
        'priority' => -20);

    return $items;
}
