<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * Implements hook_gd_dashboard_index_alter
 */
function gd_social_gd_dashboard_index_alter() {
    drupal_add_js(drupal_get_path('module', 'gd_social') . '/js/gd_social.js');
    drupal_add_css(drupal_get_path('module', 'gd_social') . '/css/gd_social.css');
    $list = gd_social_get_registered();
    foreach ($list as $l) {
        foreach ($l['js'] as $js) {
            drupal_add_js($js);
        }

        foreach ($l['css'] as $css) {
            drupal_add_css($css);
        }
    }
}

function gd_social_get_registered() {
    return module_invoke_all('gd_social_register');
}