<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


function data_controller_python_dp_datasource_option_definitions() {
    $items[PythonDataSource::TYPE] = array(
        'protocol' => array(
            'publicName' => 'Protocol',
            'required' => TRUE,
            'dictionary' => array('http', 'https')),
        'host' => array('publicName' => 'Host', 'required' => TRUE),
        'port' => array('publicName' => 'Port', 'required' => FALSE),
        'path' => array('publicName' => 'Path', 'required' => TRUE));

    return $items;
}

function data_controller_python_dp_datasource() {
    $items[PythonDataSource::TYPE] = array(
        'extensions' => array(
            'maximumEntityNameLength' => 'UnlimitedEntityNameLengthImpl'));

    return $items;
}

function data_controller_python_dp_datasource_query() {
    $items[PythonDataSource::TYPE] = array(
        'classname' => 'PythonDataSourceHandler');

    return $items;
}
