<?php
/*
 * Copyright 2014 REI Systems, Inc.
 *
 * This file is part of GovDashboard.
 *
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_xautoload()
 *
 * @param \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter
 */
function gd_health_medic_xautoload($adapter) {
    $adapter->add('GD','lib');
}

/**
 * Implementation of hook_menu
 *
 * @return array
 */
function gd_health_medic_menu () {

    $items = array();

    $items['admin/structure/govdashboard/health/medic'] = array(
        'title' => 'Medic',
        'page callback' => 'gd_health_medic_admin_page',
        'access arguments' => array('administer site configuration'),
        'file' => 'gd_health_medic.admin.php',
        'type' => MENU_LOCAL_TASK,
        'context' => MENU_CONTEXT_PAGE,
        'weight' => 0
    );

    $items['admin/structure/govdashboard/health/medic/api/treatment'] = array(
        'page callback' => 'gd_health_medic_admin_api_treatment',
        'access arguments' => array('administer site configuration'),
        'file' => 'gd_health_medic.admin.php',
        'type' => MENU_CALLBACK
    );


    return $items;
}

function gd_health_medic_treatment_apply ( $patient, $treatmentName ) {
    $medic = new GD\Health\Medic\Medic();
    $medic->applyTreatment($patient,$treatmentName);
}