<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


function data_controller_dimension_reference_dp_dimension() {
    // we use a reference to itself for the key. See implementation of DefaultDimensionFactory::findHandler() for details
    $items['ReferenceDimensionHandler'] = array(
        'classname' => 'ReferenceDimensionHandler');

    return $items;
}

function data_controller_dimension_reference_dp_dataset_assembler() {
    $items[ReferenceDimensionDatasetAssembler::DATASET_SOURCE_ASSEMBLER__TYPE] = array(
        'classname' => 'ReferenceDimensionDatasetAssembler');

    return $items;
}
