<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


function data_controller_sql_dp_log_message_listener() {
    $items[] = array(
        'classname' => 'StatementLogMessageKeeper',
        'priority' => -11);
    $items[] = array(
        'classname' => 'StatementLogMessageFormatter',
        'priority' => -10); // has to be greater than of TextLogMessageTrimmer to avoid possible SQL text truncation in log

    return $items;
}

function data_controller_sql_dp_dataset_source_type() {
    $items[TableDatasetSourceTypeHandler::SOURCE_TYPE] = array(
        'classname' => 'TableDatasetSourceTypeHandler');
    $items[SQLDatasetSourceTypeHandler::SOURCE_TYPE] = array(
        'classname' => 'SQLDatasetSourceTypeHandler');
    $items[AssemblerDatasetSourceTypeHandler::SOURCE_TYPE] = array(
        'classname' => 'AssemblerDatasetSourceTypeHandler');

    return $items;
}

function data_controller_sql_dp_formula_expression_language() {
    $items[SQLFormulaExpressionHandler::LANGUAGE__SQL] = array(
        'classname' => 'SQLFormulaExpressionHandler',
        'default' => TRUE);

    return $items;
}

function data_controller_sql_dp_formula_expression_sql_clean() {
    $items[] = array(
        'classname' => 'FormulaExpressionSQLCommentStripper',
        'priority' => 1);
    $items[] = array(
        'classname' => 'FormulaExpressionSQLWhiteCharacterStripper',
        'priority' => 10);
    $items[] = array(
        'classname' => 'IF2CASE_FormulaExpressionConverter',
        'priority' => 100);

    return $items;
}
