<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


use ADFS\Security\Authentication\Factory\ADFSAuthenticationFactory;

/**
 * Implements hook_enable()
 */
function gd_adfs_enable() {
    variable_set('user_mail_status_activated_notify', FALSE);
    variable_set('user_mail_password_reset_notify', FALSE);
    variable_set('user_mail_status_blocked_notify', FALSE);
}

/**
 * Implements hook_disable()
 */
function gd_adfs_disable() {
    variable_set('user_mail_status_activated_notify', TRUE);
    variable_set('user_mail_password_reset_notify', TRUE);
    variable_set('user_mail_status_blocked_notify', TRUE);
}

function gd_adfs_form_alter(&$form, $form_state, $form_id)  {
    if ($form_id == 'gd_login_personal_info_form') {
        unset($form['first_name']);
        unset($form['last_name']);
        unset($form['actions']);

        $form['adfs_change_info'] = array(
            '#markup' => 'Please contact your active directory administrators to change personal information.',
        );
    } else if ($form_id == 'gd_password_change_form') {
        unset($form['account']);
        unset($form['actions']);
        unset($form['#validate']);

        $form['adfs_change_info'] = array(
            '#markup' => 'Please contact your active directory administrators to change your password.',
        );
    }
}

/**
 * Implements hook_xautoload()
 *
 * @param \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter
 */
function gd_adfs_xautoload($adapter) {
    $adapter->add('ADFS','lib');
}

function gd_adfs_menu () {
    $items = array();

    $items['admin/config/govdashboard/sso/adfs'] = array(
        'title' => 'ADFS SSO Settings',
        'description' =>  'SSO handler for GovDashboard.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('gd_adfs_admin_settings_form'),
        'file' => 'gd_adfs.admin.inc',
        'access arguments' => array('administer site configuration')
    );

    return $items;
}

/**
 * Implements hook_gd_security_authentication_register
 */
function gd_adfs_gd_security_authentication_register() {
    $items = array(
        'adfs' => array(
            'weight' => -1,
            'factory' => 'ADFS\Security\Authentication\Factory\ADFSAuthenticationFactory',
            'single_sign_on' => TRUE
        )
    );

    return $items;
}

function gd_adfs_fisma_password_bypass() {
    return TRUE;
}

function gd_adfs_user_insert(&$edit, $account, $category) {
    $edit['pass'] = user_password(12);
}

function gd_adfs_gd_security_exceptions() {
    return '/^user\/login/i';
}