<?php
/*
 * Copyright 2014 REI Systems, Inc.
 * 
 * This file is part of GovDashboard.
 * 
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * Implementation of 'Distributed Transaction Processing: The XA Specification'
 * http://pubs.opengroup.org/onlinepubs/009680699/toc.pdf
 */

/**
 * Common acronyms:
 *     TM - Transaction Manager
 *     RM - Resource Manager
 *     AP - Application Program
 */

/**
 * Implementation restrictions:
 *   - in most of cases methods do not return error codes. They throw exceptions.
 *     Original specification was approved in 1991 and at that time returning error code was accepted pattern.
 *     Present-day development is based on exceptions instead
 *   - asynchronous transaction preparation/commit/rollback are not supported because
 *     PHP language does not natively support threading model
 */

define('DISTRIBUTED_TRANSACTION_MODULE_NAME', 'xa_transaction');
