<?php
/*
 * Copyright 2014 REI Systems, Inc.
 *
 * This file is part of GovDashboard.
 *
 * GovDashboard is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GovDashboard is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GovDashboard.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * Implementation of hook_menu
 *
 * @return array
 */
function gd_health_menu () {

    $items = array();

    $items['admin/structure/govdashboard/health'] = array(
        'title' => 'GovDashboard Health',
        'description' => 'System Health Utilities',
        'page callback' => 'gd_health_admin_page',
        'access arguments' => array('administer site configuration'),
        'file' => 'gd_health.admin.php',
    );

    $items['admin/structure/govdashboard/health/main'] = array(
        'title' => 'Main',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => -10,
    );

    return $items;
}